### ISSUE TITLE
pixel weights nside 8192

### ISSUE THREAD

**Issue by zonca** [healpy/healpy-data#1]
@mreineck would it be possible to also compute pixel weights for NSIDE 8192?

**Comment by mreineck** [comment]
It's quite a big effort, since it requires roughly a CPU month. I would have to make the weight generator batch-ready.
Do we have a concrete use case?

**Comment by zonca** [comment]
yes, Simons Observatory has all Large Aperture Telescope maps at 8192

**Comment by mreineck** [comment]
I'll see what I can do. Most likely I won't have results before next year though ...

**Comment by zonca** [comment]
Thanks, mid-January would be ideal, would it help if you had access to [Popeye](https://www.sdsc.edu/support/user_guides/popeye-simons.html)? 48 cores and 768 GB/node

**Comment by mreineck** [comment]
Thanks! But I should be able to use one of the MPA clusters. Actually there is a queue which might have sufficiently long runtime so that I can do this in one go...

**Comment by mreineck** [comment]
I have the data, but Github's file size limit within a repo seems to be 100MB :-/

**Comment by zonca** [comment]
Ok, I'll setup git LFS and let you know

**Comment by zonca** [comment]
git LFS doesn't support Github pages, so we could store the file in the repository, but it would not be served at https://healpy.github.io/healpy-data/

@mreineck how big is the file? can you gzip it?

**Comment by mreineck** [comment]
The file has 400MB; 373MB gzipped, so no help there...
On the other hand, this file is needed by perhaps 2 groups per year worldwide ... does it really need this kind of distribution channel?

**Comment by zonca** [comment]
Reduce to lower precision floating point numbers?

**Comment by mreineck** [comment]
Then you get a factor 2 (still not enough), and a large part of the accuracy that can be achieved with this is lost.

**Comment by zonca** [comment]
@mreineck can you please attach the file uncompressed and at high-precision to (limit for release artifacts is 2 GB): https://github.com/healpy/healpy-data/releases/edit/1.0

**Comment by mreineck** [comment]
Will do. This might take almost forever, since I'm on a bad ADSL line.

**Comment by zonca** [comment]
if you have a copy on a server can you copy it to NERSC?

**Comment by zonca** [comment]
thanks @mreineck, it is available at https://github.com/healpy/healpy-data/releases/download/1.0/healpix_full_weights_nside_8192.fits

**Comment by zonca** [comment]
had to rename the release to https://github.com/healpy/healpy-data/releases/tag/full_weights, to have the same naming.

**Comment by SergeiDBykov** [comment]
Hi, sorry for bothering, but how to use these files?  Is there a function (or an algorithm) to get each pixel weights from the file for given nside?  There are less rows than  npix.

**Comment by zonca** [comment]
It's a flag in map2alm, the filename is passed into C++, see
https://github.com/healpy/healpy/blob/8710c9fcf901a0a3e4efff37593c8d9ea17c426b/healpy/sphtfunc.py#L286

**Comment by SergeiDBykov** [comment]
@zonca Thanks, of course, but for my problem I would like to get the weights for each pixel precisely. Is it possible?

**Comment by zonca** [comment]
I don't know, you should look in the healpix C++ source code and check how
they use it.

**Comment by mreineck** [comment]
The relevant source code is in the routines `extract_fullweights()` and `apply_fullweights()` in `weight_utils.cc` of Healpix C++.  The code is a bit complicated, because it makes use of all the symmetries of the Healpix grid to only store the minimum subset of weights.
